version: "3"

services:
  pomo-backend:
    container_name: pomo-backend
    build: "."
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - postgres
    networks:
      - app-connect
    ports:
      - "3333:3333"
    env_file:
      - .env

  postgres:
    container_name: ${DB_HOST}
    image: postgres:11
    # restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app-connect
    env_file:
      - .env

volumes:
  postgres-data:

networks:
  app-connect:
    name: Pomo
